# Generated by Django 2.2 on 2020-05-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='类型名称')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签类型',
                'verbose_name_plural': '标签类型',
                'permissions': (('view_type', '查看标签类型'), ('add_type', '添加标签类型'), ('change_type', '编辑标签类型'), ('delete_type', '删除标签类型')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标签名称')),
                ('name_cn', models.CharField(max_length=100, verbose_name='中文名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Type', verbose_name='类型')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'permissions': (('view_tag', '查看标签'), ('add_tag', '添加标签'), ('change_tag', '编辑标签'), ('delete_tag', '删除标签')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('public_network', models.CharField(choices=[('z_network', 'Z网'), ('v_network', 'V网')], default='v_network', max_length=20, verbose_name='实例部署网络')),
                ('instance_name', models.CharField(max_length=22, verbose_name='实例的显示名称')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='实例的描述')),
                ('cpu', models.IntegerField(verbose_name='CPU核数')),
                ('memory', models.IntegerField(verbose_name='内存大小，单位: GB')),
                ('status', models.CharField(choices=[('Running', '运行中'), ('Starting', '启动中'), ('Stopping', '停止中'), ('Stopped', '已停止')], default='Running', max_length=8, verbose_name='实例状态')),
                ('pstatus', models.CharField(choices=[('Running', '运行中'), ('Error', '异常'), ('Stopped', '已停止')], default='Running', max_length=8, verbose_name='实例部署项目软件状态')),
                ('hostname', models.CharField(blank=True, max_length=23, null=True, verbose_name='实例机器名称')),
                ('os_type', models.CharField(default='linux', max_length=10, verbose_name='操作系统类型')),
                ('os_name', models.CharField(default='', max_length=20, verbose_name='操作系统名称')),
                ('instance_project_type', models.CharField(choices=[('Develop', '开发中'), ('Maintain', '运维中')], default='Maintain', max_length=16, verbose_name='实例项目阶段')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.ManyToManyField(blank=True, to='cmdb.Tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'permissions': (('view_host', '查看主机'), ('change_host', '更新主机信息')),
                'default_permissions': (),
            },
        ),
    ]
