# Generated by Django 2.2 on 2020-05-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20200524_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='instance_name',
            new_name='name',
        ),
    ]
