# Generated by Django 2.2 on 2020-04-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='用户名', max_length=10)),
                ('name', models.CharField(help_text='姓名', max_length=10)),
                ('phone', models.CharField(help_text='手机', max_length=11)),
                ('password', models.CharField(help_text='密码', max_length=32)),
                ('sex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True)),
            ],
        ),
    ]
