# Generated by Django 2.2 on 2020-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='P_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=20)),
                ('project_type', models.IntegerField(blank=True, choices=[(0, '故障'), (1, 'BUG'), (2, '需求'), (3, '逾期|放弃')], null=True)),
                ('start_date', models.DateField(auto_now_add=True, help_text='开始时间')),
                ('end_date', models.CharField(help_text='结束时间', max_length=25)),
                ('res_name', models.CharField(help_text='主要负责人', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='项目状态')),
                ('state', models.IntegerField(blank=True, choices=[(0, '正在进行'), (1, '失败'), (2, '延迟'), (3, '完成')], null=True)),
            ],
        ),
    ]
