# Generated by Django 2.2 on 2020-05-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='联系人姓名')),
                ('sex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True)),
                ('occupation', models.CharField(max_length=22, verbose_name='职务')),
                ('company', models.CharField(max_length=22, verbose_name='所属公司')),
                ('project', models.CharField(max_length=22, verbose_name='所属项目')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('type', models.IntegerField(choices=[(0, '客户'), (1, '友商'), (2, '内部')], default=0, verbose_name='联系人类别')),
            ],
            options={
                'verbose_name': '联系人信息',
            },
        ),
    ]
