# Generated by Django 2.2 on 2020-04-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(help_text='作者', to='books.Author', verbose_name='作者'),
        ),
    ]
