# Generated by Django 2.2 on 2020-04-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用户名', max_length=20)),
                ('password', models.CharField(help_text='密码', max_length=32)),
                ('tel', models.CharField(help_text='电话', max_length=11)),
                ('email', models.CharField(help_text='邮箱', max_length=35)),
                ('sex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True)),
                ('skill', models.IntegerField(blank=True, choices=[(0, 'Python'), (1, 'Java'), (2, 'PHP'), (3, 'C#')], null=True)),
            ],
        ),
    ]
